// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxJ86CiHeffNHelWqnt-UL7qrx6VoQSc',
    appId: '1:653711544561:web:032742ddea4de33a65d950',
    messagingSenderId: '653711544561',
    projectId: 'coolapp-14330',
    authDomain: 'coolapp-14330.firebaseapp.com',
    storageBucket: 'coolapp-14330.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwf2lCjQ5PXgo2Jf_rH97GXkJkbtViUDI',
    appId: '1:653711544561:android:926baa038c98bda565d950',
    messagingSenderId: '653711544561',
    projectId: 'coolapp-14330',
    storageBucket: 'coolapp-14330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2b66JV6eLiAC7EN098YCh1HeEjoJXLv0',
    appId: '1:653711544561:ios:1483bd2234bf57b265d950',
    messagingSenderId: '653711544561',
    projectId: 'coolapp-14330',
    storageBucket: 'coolapp-14330.appspot.com',
    iosClientId: '653711544561-nrffodbim2rtia52dun79j5cmn53gt9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2b66JV6eLiAC7EN098YCh1HeEjoJXLv0',
    appId: '1:653711544561:ios:1483bd2234bf57b265d950',
    messagingSenderId: '653711544561',
    projectId: 'coolapp-14330',
    storageBucket: 'coolapp-14330.appspot.com',
    iosClientId: '653711544561-nrffodbim2rtia52dun79j5cmn53gt9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolApp',
  );
}
